name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker-compose up --build -d

      - name: Deploy to AWS
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name my-stack \
            --parameter-overrides \
              DBHost=${{ secrets.DB_HOST }} \
              DBUser=${{ secrets.DB_USER }} \
              DBPass=${{ secrets.DB_PASS }} \
              DBName=${{ secrets.DB_NAME }}

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}
